

name: Caching file

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-type: pro
      with:
        path: ./testdir
        key: ${{ runner.os }}-build-${{ env.cache-type }}-${{ hashFiles('**/1.txt') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-type }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Generate cachestr
      if: steps.${{ runner.os }}-build-${{ env.cache-type }}-${{ hashFiles('**/1.txt') }}.outputs.cache-hit != 'true'
      run: echo "run Generate.sh";# not found cachestr
