

name: Caching file2

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ls  ./
      run: ls -l
    - name: cat  ./
      run: cat ./1.txt
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-type: pro
      with:
        path: ./
        key: ${{ runner.os }}-build-${{ env.cache-type }}-${{ hashFiles('./1.txt') }}
    - name: Cache str
      id: cachestr
      uses: actions/cache@v2
      with:
        path: cachestr
        key: ${{ runner.os }}-build-${{ env.cache-type }}-${{ hashFiles('./1.txt') }}

    - name: ls  ./
      run: ls -l
    - name: hash
      run: echo ${{ hashFiles('./1.txt') }}
    - name: cat  ./
      run: cat ./1.txt
    - name: Generate cachestr
      if: steps.cachestr.outputs.cache-hit != 'true'
      run: rm -rf ./1.txt;echo "rm file";echo "run Generate.sh";
