

name: Caching file2

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rm
      run: echo "rm";#rm -rf ./1.txt
    - name: ls  ./
      run: ls -l
    - name: cat  ./
      run: cat ./1.txt
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-type: pro
      with:
        path: ./2.txt
        key: ${{ runner.os }}-build-${{ env.cache-type }}-${{ hashFiles('./1.txt') }}

    - name: ls  ./
      run: ls -l
    - name: hash
      run: echo ${{ hashFiles('./1.txt') }}
    - name: cat  ./
      run: cat ./1.txt
