

name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Primes
      id: cachestr
      uses: actions/cache@v2
      with:
        path: cachestr
        key: ${{ runner.os }}-primes

    - name: Generate cachestr
      if: steps.cachestr.outputs.cache-hit != 'true'
      run: echo "run Generate.sh";# not found cachestr

    - name: Use cachestr
      run: echo "use cache:cachestr";
