# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  cache-type: pro
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
        
    - name: save cache
      id: cachefilehash
      uses: actions/cache@v2
      with:
        path: cachefilehash
        key: ${{ runner.os }}-build-${{ env.cache-type }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-type }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
          
          
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-type }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-type }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          



    - name: ls  
      run: cd ./testdir;ls -l
      
      
    - name: Generate cache is false .Build with Maven.It takes a long time(For example, 3 hours)
      run: mvn -B package --file ./testdir/pom.xml
      if: steps.cachefilehash.outputs.cache-hit == 'false'


    - name: Generate cache is true.Do nothing.
      if: steps.cachefilehash.outputs.cache-hit == 'true'
      run: echo "found cache,using cache.Don't rebuild";
